telegram:
  botName: devmark_ru_test_bot
  token: 7071822713:AAHmSIKAAZLTww3mwN8m1wQ4y-geKZ9i1d0

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
<<<<<<< HEAD
    url: jdbc:postgresql://localhost:5432/tg_bot_db
=======
    url: jdbc:postgresql://localhost:5432/tg_bot
>>>>>>> 5cf757e (complite beta version 1.1)
    username: postgres
    password: "5290768"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false


attributesBot:
  youtube_attribute: YouTube
  tiktok_attribute: TikTok
  instagram_attribute: Instagram
  telegraph_attribute: Telegraph
  youtube: (https://www.youtube.com/)
  tiktok: (https://www.tiktok.com/explore)
  instagram: (https://www.instagram.com/)
  telegraph: (https://telegra.ph/)

chatId:
  group: -1002115452577

head_message:
  name: SKcrypto
  link: (https://t.me/DefiSKcrypto)

gameName:
  kgb: KGB Protokol Bot
  playCornBattles: Play Corn Battles
  hamsterdam: Hamsterdam
  zarGates: ZarGates Retrodrop
  qappiMiner: Qappi Miner
  pocketFi: PocketFi
  cexIOPowerTap: CEX.IO Power Tap
  sphinx: Sphinx
  betFury: BetFury Cryptodrop
  harvestMoon: HarvestMoonBot
  okxRacer: OKX Racer
  richAnimals: Rich Animals
  signie: Signie
  hamsterKombat: Hamster Kombat
  mtkClickerMafia: $MTK Clicker Mafia
  earthCoin: Earth Coin
  1winToken: 1 win Token
  w-coin: W-Coin
  flareX: Flare X
  shuttle: Shuttle
  claytonGame: Clayton Game
  gatto: Gatto | Game (18+)
  tronSpaceApp: Tron Space App
  muskEmpire: Musk Empire
  tonMining: TON Mining
  pixelWallet: Pixel Wallet
  catGoldMiner: Cat Gold Miner
  notcoin: Notcoin
  cityHolderGame: CITY Holder Game
  frogFarm: FrogFarm
  yescoinWhite: Yescoin (White)
  brrrrrGame: brrrrr game
  timecoinMineYourTime: TimeCoin - mine your time
  dogs: Dogs
  zavodWallet: ZAVOD Wallet
  pixelTapByPixelverse: PixelTap by PixelVerse
  limeCoin: LimeCoin
  timeFarm: Time Farm
  djDog: DJDOG | New Reward Task
  yescoinYellow: Yescoin (Yellow)
  pretonDrop: $PRETON DROP
  hotWallet: HOT Wallet
  tonStation: TON Station
  tonBitcoinTBTC: TonBitcoin (tBTC) | Mine-2-Earn
  blum: Blum
  catizen: Catizen
  bitton: Bitton
  vertus: Vertus
  seedApp: SEED App - Mine SEED
  memeFiCoin: MemeFi Coin
  bcoin2048: Bcoin 2048
  duckCoin: DuckCoin
  dotcoin: Dotcoin
  cubes?: Cubes?
  xBlastApp: xBLAST APP - Mine XBL
  ogCommunityBot: OGCOmmunity Bot
  tapSwap: TapSwap
  fuelMining: Fuel Mining
  holdWallet: HOLD Wallet

gameLink:
  kgb: (t.me/DefiSKcrypto)
  playCornBattles: (t.me/DefiSKcrypto)
  hamsterdam: (t.me/DefiSKcrypto)
  zarGates: (t.me/DefiSKcrypto)
  qappiMiner: (t.me/DefiSKcrypto)
  pocketFi: (t.me/DefiSKcrypto)
  cexIOPowerTap: (t.me/DefiSKcrypto)
  sphinx: (t.me/DefiSKcrypto)
  betFury: (t.me/DefiSKcrypto)
  harvestMoon: (t.me/DefiSKcrypto)
  okxRacer: (t.me/DefiSKcrypto)
  richAnimals: (t.me/DefiSKcrypto)
  signie: (t.me/DefiSKcrypto)
  hamsterKombat: (t.me/DefiSKcrypto)
  mtkClickerMafia: (t.me/DefiSKcrypto)
  earthCoin: (t.me/DefiSKcrypto)
  1winToken: (t.me/DefiSKcrypto)
  w-coin: (t.me/DefiSKcrypto)
  flareX: (t.me/DefiSKcrypto)
  shuttle: (t.me/DefiSKcrypto)
  claytonGame: C(t.me/DefiSKcrypto)
  gatto: (t.me/DefiSKcrypto)
  tronSpaceApp: (t.me/DefiSKcrypto)
  muskEmpire: (t.me/DefiSKcrypto)
  tonMining: (t.me/DefiSKcrypto)
  pixelWallet: (t.me/DefiSKcrypto)
  catGoldMiner: (t.me/DefiSKcrypto)
  notcoin: (t.me/DefiSKcrypto)
  cityHolderGame: (t.me/DefiSKcrypto)
  frogFarm: (t.me/DefiSKcrypto)
  yescoinWhite: (t.me/DefiSKcrypto)
  brrrrrGame: (t.me/DefiSKcrypto)
  timecoinMineYourTime: (t.me/DefiSKcrypto)
  dogs: (t.me/DefiSKcrypto)
  zavodWallet: (t.me/DefiSKcrypto)
  pixelTapByPixelverse: (t.me/DefiSKcrypto)
  limeCoin: (t.me/DefiSKcrypto)
  timeFarm: (t.me/DefiSKcrypto)
  djDog: (t.me/DefiSKcrypto)
  yescoinYellow: (t.me/DefiSKcrypto)
  pretonDrop: (t.me/DefiSKcrypto)
  hotWallet: (t.me/DefiSKcrypto)
  tonStation: (t.me/DefiSKcrypto)
  tonBitcoinTBTC: (t.me/DefiSKcrypto)
  blum: (t.me/DefiSKcrypto)
  catizen: (t.me/DefiSKcrypto)
  bitton: (t.me/DefiSKcrypto)
  vertus: (t.me/DefiSKcrypto)
  seedApp: (t.me/DefiSKcrypto)
  memeFiCoin: (t.me/DefiSKcrypto)
  bcoin2048: (t.me/DefiSKcrypto)
  duckCoin: (t.me/DefiSKcrypto)
  dotcoin: (t.me/DefiSKcrypto)
  cubes?: (t.me/DefiSKcrypto)
  xBlastApp: (t.me/DefiSKcrypto)
  ogCommunityBot: (t.me/DefiSKcrypto)
  tapSwap: (t.me/DefiSKcrypto)
  fuelMining: (t.me/DefiSKcrypto)
  holdWallet: (t.me/DefiSKcrypto)