package com.example.demo_bot.model

import org.springframework.stereotype.Component

@Component
class GameNameAttributes {

    val kgb = GameNameModel("KGB Protokol Bot", "(t.me/DefiSKcrypto)")
    val playCornBattles = GameNameModel("Play Corn Battles", "(t.me/DefiSKcrypto)")
    val hamsterdam = GameNameModel("Hamsterdam", "(t.me/DefiSKcrypto)")
    val zarGates = GameNameModel("ZarGates Retrodrop", "(t.me/DefiSKcrypto)")
    val qappiMiner = GameNameModel("Qappi Miner", "(t.me/DefiSKcrypto)")
    val pocketFi = GameNameModel("PocketFi", "(t.me/DefiSKcrypto)")
    val cexIOPowerTap = GameNameModel("CEX.IO Power Tap", "(t.me/DefiSKcrypto)")
    val sphinx = GameNameModel("Sphinx", "(t.me/DefiSKcrypto)")
    val betFury = GameNameModel("BetFury Cryptodrop", "(t.me/DefiSKcrypto)")
    val harvestMoon = GameNameModel("HarvestMoonBot", "(t.me/DefiSKcrypto)")
    val okxRacer = GameNameModel("OKX Racer", "(t.me/DefiSKcrypto)")
    val richAnimals = GameNameModel("Rich Animals", "(t.me/DefiSKcrypto)")
    val signie = GameNameModel("Signie", "(t.me/DefiSKcrypto)")
    val hamsterKombat = GameNameModel("Hamster Kombat", "(t.me/DefiSKcrypto)")
    val mtkClickerMafia = GameNameModel("MTK Clicker Mafia", "(t.me/DefiSKcrypto)")
    val earthCoin = GameNameModel("Earth Coin", "(t.me/DefiSKcrypto)")
    val winToken = GameNameModel("1 win Token", "(t.me/DefiSKcrypto)")
    val wCoin = GameNameModel("W-Coin", "(t.me/DefiSKcrypto)")
    val flareX = GameNameModel("Flare X", "(t.me/DefiSKcrypto)")
    val shuttle = GameNameModel("Shuttle", "(t.me/DefiSKcrypto)")
    val claytonGame = GameNameModel("Clayton Game", "(t.me/DefiSKcrypto)")
    val gatto = GameNameModel("Gatto | Game (18+)", "(t.me/DefiSKcrypto)")
    val tronSpaceApp = GameNameModel("Tron Space App", "(t.me/DefiSKcrypto)")
    val muskEmpire = GameNameModel("Musk Empire", "(t.me/DefiSKcrypto)")
    val tonMining = GameNameModel("TON Mining", "(t.me/DefiSKcrypto)")
    val pixelWallet = GameNameModel("Pixel Wallet", "(t.me/DefiSKcrypto)")
    val catGoldMiner = GameNameModel("Cat Gold Miner", "(t.me/DefiSKcrypto)")
    val notcoin = GameNameModel("Notcoin", "(t.me/DefiSKcrypto)")
    val cityHolderGame = GameNameModel("CITY Holder Game", "(t.me/DefiSKcrypto)")
    val frogFarm = GameNameModel("FrogFarm", "(t.me/DefiSKcrypto)")
    val yescoinWhite = GameNameModel("Yescoin (White)", "(t.me/DefiSKcrypto)")
    val brrrrrGame = GameNameModel("brrrrr game", "(t.me/DefiSKcrypto)")
    val timecoinMineYourTime = GameNameModel("TimeCoin - mine your time", "(t.me/DefiSKcrypto)")
    val dogs = GameNameModel("Dogs", "(t.me/DefiSKcrypto)")
    val zavodWallet = GameNameModel("ZAVOD Wallet", "(t.me/DefiSKcrypto)")
    val pixelTapByPixelverse = GameNameModel("PixelTap by PixelVerse", "(t.me/DefiSKcrypto)")
    val limeCoin = GameNameModel("LimeCoin", "(t.me/DefiSKcrypto)")
    val timeFarm = GameNameModel("Time Farm", "(t.me/DefiSKcrypto)")
    val djDog = GameNameModel("DJDOG | New Reward Task", "(t.me/DefiSKcrypto)")
    val yescoinYellow = GameNameModel("Yescoin (Yellow)", "(t.me/DefiSKcrypto)")
    val pretonDrop = GameNameModel("PRETON DROP", "(t.me/DefiSKcrypto)")
    val hotWallet = GameNameModel("HOT Wallet", "(t.me/DefiSKcrypto)")
    val tonStation = GameNameModel("TON Station", "(t.me/DefiSKcrypto)")
    val tonBitcoinTBTC = GameNameModel("TonBitcoin (tBTC) | Mine-2-Earn", "(t.me/DefiSKcrypto)")
    val blum = GameNameModel("Blum", "(t.me/DefiSKcrypto)")
    val catizen = GameNameModel("Catizen", "(t.me/DefiSKcrypto)")
    val bitton = GameNameModel("Bitton", "(t.me/DefiSKcrypto)")
    val vertus = GameNameModel("Vertus", "(t.me/DefiSKcrypto)")
    val seedApp = GameNameModel("SEED App - Mine SEED", "(t.me/DefiSKcrypto)")
    val memeFiCoin = GameNameModel("MemeFi Coin", "(t.me/DefiSKcrypto)")
    val bcoin2048 = GameNameModel("Bcoin 2048", "(t.me/DefiSKcrypto)")
    val duckCoin = GameNameModel("DuckCoin", "(t.me/DefiSKcrypto)")
    val dotcoin = GameNameModel("Dotcoin", "(t.me/DefiSKcrypto)")
    val cubes = GameNameModel("Cubes?", "(t.me/DefiSKcrypto)")
    val xBlastApp = GameNameModel("xBLAST APP - Mine XBL", "(t.me/DefiSKcrypto)")
    val ogCommunityBot = GameNameModel("OGCOmmunity Bot", "(t.me/DefiSKcrypto)")
    val tapSwap = GameNameModel("TapSwap", "(t.me/DefiSKcrypto)")
    val fuelMining = GameNameModel("Fuel Mining", "(t.me/DefiSKcrypto)")
    val holdWallet = GameNameModel("HOLD Wallet", "(t.me/DefiSKcrypto)")

}